services: 
  backend:
    env_file:
      - ./.env
    build:
     context: app
     target: builder
    ports: 
      - '8000:8000'
    depends_on:
      - db
    develop:
      watch:
        - action: sync+restart
          path: ./app
          target: /app
  db:
    container_name: postgres_meta_motion
    image: postgres:latest
    env_file:
      - ./.env
    volumes:
      - ./db_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
    restart: always
  pgadmin:
    image: 'docker.io/dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - 15080:80
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin/
    depends_on:
      - db
    user: "${UID}:${GID}"
