services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - JWT_SECRET_KEY=secret
    depends_on:
      - db
    develop:
      watch:
        - action: sync+restart
          path: ./app
          target: /app
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: always
  pgadmin:
    image: "docker.io/dpage/pgadmin4:latest"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@meta-motion.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 15080:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin/
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    user: "${UID}:${GID}"

volumes:
  postgres_data:
  pgadmin_data:
