"""Update role and user model

Revision ID: 2463ef627253
Revises: 25f7133448b0
Create Date: 2025-05-22 12:35:46.269567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2463ef627253'
down_revision = '25f7133448b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_role_id_fkey', type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('users_role_id_fkey', 'roles', ['role_id'], ['id'])

    op.drop_table('users_roles')
    # ### end Alembic commands ###
