"""Change mac address type

Revision ID: db115082f40d
Revises: dc36c00432bf
Create Date: 2025-05-31 14:24:18.686931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db115082f40d'
down_revision = 'dc36c00432bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_index('ix_sensors_mac')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.create_index('ix_sensors_mac', ['mac'], unique=True)

    # ### end Alembic commands ###
