"""Add sensors saving

Revision ID: dc36c00432bf
Revises: 2463ef627253
Create Date: 2025-05-31 14:20:22.384890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc36c00432bf'
down_revision = '2463ef627253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_login', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['user_login'], ['users.login'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensors_mac'), ['mac'], unique=True)

    op.create_table('samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('watch_on_hand', sa.String(length=50), nullable=False),
    sa.Column('acceleration', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('gyroscope', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_samples_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_samples_timestamp'))

    op.drop_table('samples')
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensors_mac'))

    op.drop_table('sensors')
    # ### end Alembic commands ###
